services:

  wg-quickrs-agent-init-local:
    extends:
      file: docker-compose.yml
      service: wg-quickrs-agent-init
    image: ''
    build:
      dockerfile: src/Dockerfile
      target: runner

  wg-quickrs-agent-run-local:
    extends:
      file: docker-compose.yml
      service: wg-quickrs-agent-run
    image: ''
    build:
      dockerfile: src/Dockerfile
      target: runner
    restart: no

  wg-quickrs-config-reset-password-local:
    extends:
      file: docker-compose.yml
      service: wg-quickrs-config-reset-password
    image: ''
    build:
      dockerfile: src/Dockerfile
      target: runner

