services:

  wg-quickrs-runner:
    build:
      dockerfile: src/Dockerfile
      target: runner
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv4.conf.all.src_valid_mark=1
    volumes:
      - .wg-quickrs-docker:/app/.wg-quickrs

  wg-quickrs-agent-run:
    container_name: wg-quickrs-agent-run-cnt
    extends:
      service: wg-quickrs-runner
    ports:
      - "80:80/tcp"
      - "443:443/tcp"
      - "51820:51820/udp"
    command: [ "agent", "run" ]

